### ISSUE TITLE
Missing books/repo move

### ISSUE THREAD

**Issue by bmschmidt** [mfall3/HTRC-Bookworm#7]
How many volumes should this script return? Running my fork, I just ended up with a Bookworm of 1686152. I think I see that Peter's branch fixes a truncated result problem; mine fixes an array problem that's very problematic. Peter's changes may get us up to the appropriate amount. Tagging @organisciak as well.

My code will also actually build a Bookworm using the titles of the works as their text. This can be very useful for debugging/anticipating problems. [Example chart](http://benschmidt.org/D3/#%7B%22database%22%3A%22catalogworm%22%2C%22plotType%22%3A%22streamgraph%22%2C%22method%22%3A%22return_json%22%2C%22search_limits%22%3A%7B%22date_year%22%3A%7B%22%24gte%22%3A1700%2C%22%24lte%22%3A2020%7D%7D%2C%22aesthetic%22%3A%7B%22x%22%3A%22date_year%22%2C%22y%22%3A%22TextCount%22%2C%22fill%22%3A%22lc_classes%22%7D%2C%22counttype%22%3A%5B%22TextCount%22%5D%2C%22groups%22%3A%5B%22date_year%22%2C%22lc_classes%22%5D%7D)

Could we move this repo on the main Bookworm-Project site to ease the process of integrating all these changes? Perhaps rename it to "Hathifiles-Bookworm" (the actual naming convention would be "Hath-Bookworm," but that's too close to the name of the grant.)

**Comment by mfall3** [comment]
This script should currently create a catalog file for ~5 million volumes.

**Comment by mfall3** [comment]
I have transferred the repo to the main Bookworm-Project site and named it HTRC-Bookworm.  Others can rename it, but I don’t think we want to codify the involvement of the Hathifiles.  HathiTrust-Bookworm or Hathi-Bookworm might be good alternatives.

**Comment by bmschmidt** [comment]
Renamed to "HathiTrust-Bookworm" because the general convention is
"$(CorpusName)-Bookworm". Possibly it should be called "HathiPD-Bookworm;"
but ideally this code could be run on the closed stuff too, if there's a
Solr endpoint.

**Comment by organisciak** [comment]
Guys, I'm going to rename this, because it is _not_ Bookworm, it's just a script for collecting metadata. It's not quite right with (anything)-Bookworm.

Also, I thought we already discussed the repo move. After Uncamp, it was going to be ported to the HTRC organization. It needs to be documented and organized properly first, and we have a naming convention. Do you guys disagree? Is seems more sensible in the HTRC organization.

For now, I'll work on improving the documentation if others intend to use it.

**Comment by organisciak** [comment]
About the size: There should be 4.8 million books. 

Were you using my fork of this codebase? If not, then you may have been simply missing results, as the rows param was set to it's default of ten results. 

Possibly, there may also be errors from hitting the server too much, but I'm not sure. How fast were you make consecutive pings? Also, were you pinging for all 14mil hathifiles, or did you trim the list? I assume you didn't have the list of IDs in the 4.8 million, I can email this to you.

For comparison, I've been running this script overnight on a 4.5m list and it's approaching 3m records.

**Comment by mfall3** [comment]
I think it should be in a place where everyone who is expected to contribute can do so without a pull request.  -Colleen

**Comment by bmschmidt** [comment]
The reason my initial impulse was to call it the hathifiles bookworm is because it creates a bookworm from the metadata. This is much more useful than it might initially sound. (Though we'll want to edit the readme to explain that it's internal code people shouldn't be using).

I thought on the basis of a conversation a few weeks ago we were going to keep it in this Bookworm repo. We can move it eventually elsewhere if necessary. I just wanted to quickly get everyone on the same repo because we're each missing important commits

This repo incorporates all of my and Peter's edits. I'm hopeful I'll get to 5,000,000 with my current process. Peter, if you haven't taken mine you'll probably need to stop and do so--check the tail of your jsoncatalog.txt, but unless it's a python version thing peculiar to me I get thousands of erroneous entires in the "lc_classes" fields.

**Comment by organisciak** [comment]
Okay, let's keep it here, which gives us less pressure to abide by the HTRC conventions for collaboration and naming. Can we add '-Metadata' to the repo? I won't change it, letting you guys vote. Or, acknowledging Ben's point about creating a Bookworm from it, then make HTMetadata-Bookworm.

Ben, I'll pull the newest version with your changes. Thanks for looking at this.

**Comment by organisciak** [comment]
I pushed the 4.8mil ID list in the newest commit. You can truncate a hathifile against that if you want a faster process and hopefully avoid some of the holes in the data.

Note that since I'm only been working with the full PD since last night, there's an unaccounted bug in `select-hathiline.py`: it gets 4.5million. This is likely a faster fix than an issue to report, but I have to catch a flight first.

**Comment by organisciak** [comment]
Ah, I put up an issue anyway :)

**Comment by organisciak** [comment]
1. Good name :)
2. I think the missing books issue discussed here was simply the 10 record response limit, which is solved.

Closing.
